apiVersion: v2
name: notif
description: Chart Helm du service notif - DevHub Campus
type: application
version: 0.1.0
appVersion: "0be2f01"
maintainers:
  - name: Pepin Maelic
    email: pepin-maelic@example.local
