apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: notif-preview
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          owner: PepMama
          repo: esgi-tp-argoCD
          tokenRef:
            secretName: github-token
            key: token
        requeueAfterSeconds: 60
  template:
    metadata:
      name: notif-preview-{{branch_slug}}
      labels:
        devhub.io/env: preview
        devhub.io/service: notif
    spec:
      project: devhub
      source:
        repoURL: https://github.com/PepMama/esgi-tp-argoCD.git
        targetRevision: '{{branch}}'
        path: devhub-campus/services/notif/chart
        helm:
          valueFiles:
            - values-preview.yaml
          parameters:
            - name: ingress.host
              value: '{{branch_slug}}.devhub.local'
      destination:
        server: https://kubernetes.default.svc
        namespace: devhub-preview-{{branch_slug}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
