# AppProject ArgoCD : devhub
# Brique de sécurité : limite les dépôts et destinations autorisés.

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devhub
  namespace: argocd
spec:
  description: Plateforme DevHub Campus

  sourceRepos:
    - https://github.com/PepMama/esgi-tp-argoCD.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: devhub-*
    - server: https://kubernetes.default.svc
      namespace: argocd

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
